quitOnTopLevelReturn: false
promptToReturnFromSubprocess: false
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
git:
  # commitPrefixes:
  #   something-main:
  #     - pattern: "^\\w+\\/(\\w+-\\w+).*"
  #       replace: "$1 "
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
gui:
  nerdFontsVersion: "3"
  sidePanelWidth: 0.3
  mainPanelSplitMode: "vertical"
  theme:
    inactiveBorderColor:
      - "#4A5568"
    selectedLineBgColor:
      - "#2D3748"
    cherryPickedCommitBgColor:
      - "#1f2335"
    cherryPickedCommitFgColor:
      - "#0BC5EA"
      - bold
  # authorColors:
  #   "*": blue
  branchColors:
    feature: white
    bugfix: red
    develop: blue
    master: magenta
    main: magenta
customCommands:
  - key: "<c-a>"
    description: "Generate AI Commit Message"
    context: "files"
    loadingText: "Generating commit message with Gemini..."
    command: >
      git diff --cached | gemini "Generate a git commit message for these changes following Conventional Commits. Return ONLY the raw commit message, no markdown, no explanation." > .git/COMMIT_EDITMSG && git commit -e -F .git/COMMIT_EDITMSG

    output: terminal
